- name: Enable IP Forwarding
  hosts: servers
  become: yes
  tasks:
  - name: Set net.ipv4.ip_forward to 1
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      state: present
      reload: yes
      sysctl_set: yes

- name: Configure LAN interface to use the new LAN CIDR
  hosts: servers
  become: yes
  tasks:
  - name: Delete the previous DHCP client configuration for the LAN interface
    ansible.builtin.shell: nmcli connection delete {{ lan_interface }} || true
    changed_when: false

  - name: Create a new connection for the LAN interface with a static IP
    ansible.builtin.shell: |
      nmcli connection add type ethernet con-name {{ lan_interface }}-static \
        ifname {{ lan_interface }} ipv4.method manual \
        ipv4.addresses "{{ lan_cidr_gateway }}/{{ lan_cidr_netmask }}"

  - name: Bring up the LAN interface
    ansible.builtin.shell: nmcli connection up {{ lan_interface }}-static

  - name: Ensure the LAN interface is configured with the correct IP address
    ansible.builtin.shell: ip addr show {{ lan_interface }} | grep -q "{{ lan_cidr_gateway }}"
    changed_when: false

- name: Configure nftables
  hosts: servers
  become: yes
  tasks:
  - name: Install nftables package
    ansible.builtin.package:
      name: nftables
      state: present

  - name: Deploy nftables configuration
    ansible.builtin.template:
      src: ../templates/nftables.conf.j2
      dest: /etc/nftables.conf
      mode: '0644'
      validate: 'nft -c -f %s'
    notify: Reload nftables

  - name: Ensure nftables service is started and enabled
    ansible.builtin.systemd:
      name: nftables
      state: started
      enabled: true

  handlers:
  - name: Reload nftables
    ansible.builtin.systemd:
      name: nftables
      state: reloaded

# Used for DHCP and DNS services
# but, the dns server could be disabled to use pihole's dns server instead
- name: Configure dnsmasq
  hosts: servers
  become: yes
  tasks:
  - name: Install dnsmasq package
    ansible.builtin.package:
      name: dnsmasq
      state: present

- name: Configure hostapd
  hosts: servers
  become: yes
  tasks:
  - name: Install hostapd package
    ansible.builtin.package:
      name: hostapd
      state: present
